version: '3.9'
services:
  db:
    image: postgres:16.3
    ports:
      - "5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    volumes:
      - .:/app
    image: lord-of-the-rings:latest
    command: python manage.py runserver
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432=value
